SRC = ./src/main.c ./src/brinquedo.c ./src/lista.c ./src/pilha.c ./src/fila.c
HEADERS = ./src/brinquedo.h ./src/lista.h ./src/pilha.h ./src/fila.h
OUT = brinquedos
all:
	gcc $(HEADERS) $(SRC) -o $(OUT)
run:
	./$(OUT)
